name: Build Game for Multiple Platforms

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: dino_game.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact: dino_game-arm64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: dino_game-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: dino_game-macos-intel
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: dino_game-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libudev-dev libxkbcommon-dev
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Rename Windows executable
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        if [ "${{ matrix.target }}" = "aarch64-pc-windows-msvc" ]; then
          mv target/${{ matrix.target }}/release/dino_game.exe target/${{ matrix.target }}/release/dino_game-arm64.exe
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          target/${{ matrix.target }}/release/dino_game.exe
          target/${{ matrix.target }}/release/dino_game-arm64.exe
          target/${{ matrix.target }}/release/dino_game-linux
          target/${{ matrix.target }}/release/dino_game-macos-intel
          target/${{ matrix.target }}/release/dino_game-macos-arm64
        if-no-files-found: ignore
