name: Build Game for Multiple Platforms

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: dino_game.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact: dino_game-arm64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: dino_game-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: dino_game-macos-intel
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: dino_game-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libudev-dev libxkbcommon-dev
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare artifact
      shell: bash
      run: |
        # 创建统一的文件名
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          if [[ "${{ matrix.target }}" == "aarch64-pc-windows-msvc" ]]; then
            cp target/${{ matrix.target }}/release/dino_game.exe ${{ matrix.artifact }}
          else
            cp target/${{ matrix.target }}/release/dino_game.exe ${{ matrix.artifact }}
          fi
        else
          # Linux 和 macOS 没有 .exe 扩展名
          cp target/${{ matrix.target }}/release/dino_game ${{ matrix.artifact }}
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}
